name: UX Audit Pro CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install @auth0/nextjs-auth0@3.5.0 --save-exact

      - name: Setup environment variables
        run: |
          echo "NEXT_PUBLIC_APP_NAME=UX Audit Pro" >> .env
          echo "NEXT_PUBLIC_APP_URL=http://localhost:3000" >> .env
          echo "AUTH0_SECRET=dummy-secret-for-ci" >> .env
          echo "AUTH0_BASE_URL=http://localhost:3000" >> .env
          echo "AUTH0_ISSUER_BASE_URL=https://dummy.auth0.com" >> .env
          echo "AUTH0_CLIENT_ID=dummy-client-id" >> .env
          echo "AUTH0_CLIENT_SECRET=dummy-client-secret" >> .env
          echo "MONGODB_URI=mongodb://dummy:dummy@localhost:27017/test" >> .env

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
        env:
          CI: true
          NODE_ENV: production